src\cs.unittests.alox\Tests_Tutorial.cs(246):.Tut_Exception()     [00:00.000  +036 Âµs] [T:(7)] [WRN] [MYDOM]: >> Logging an exception: 
src\cs.unittests.alox\Tests_Tutorial.cs(246):.Tut_Exception()                                                 >>   Type:       System.Exception
src\cs.unittests.alox\Tests_Tutorial.cs(246):.Tut_Exception()                                                 >>   Message:    TestException Message
src\cs.unittests.alox\Tests_Tutorial.cs(246):.Tut_Exception()                                                 >>   HResult:    0x80131500
src\cs.unittests.alox\Tests_Tutorial.cs(246):.Tut_Exception()                                                 >>   Inner:   
src\cs.unittests.alox\Tests_Tutorial.cs(246):.Tut_Exception()                                                 >>     Type:       System.Exception
src\cs.unittests.alox\Tests_Tutorial.cs(246):.Tut_Exception()                                                 >>     Message:    InnerException Message
src\cs.unittests.alox\Tests_Tutorial.cs(246):.Tut_Exception()                                                 >>     HResult:    0x80131500
src\cs.unittests.alox\Tests_Tutorial.cs(246):.Tut_Exception()                                                 >>     Inner:   
src\cs.unittests.alox\Tests_Tutorial.cs(246):.Tut_Exception()                                                 >>       Type:       System.Exception
src\cs.unittests.alox\Tests_Tutorial.cs(246):.Tut_Exception()                                                 >>       Message:    Inner, inner Exception
src\cs.unittests.alox\Tests_Tutorial.cs(246):.Tut_Exception()                                                 >>       HResult:    0x80131500